Models/AnimalModel.cs
namespace ZooApp.Models
{
    public class AnimalModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ZooApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SponsorFormModel.cs
using System.Collections.Generic;

namespace ZooApp.Models
{
    public class SponsorFormModel : SponsorModel
    {
        public List<AnimalModel> Animals { get; set; }
        public SponsorFormModel(List<AnimalModel> animals)
        {
            Animals = animals;
        }
        public SponsorFormModel()
        {
            Animals = new List<AnimalModel>();
        }
    }
}

Models/SponsorModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using ZooApp.Services;

namespace ZooApp.Models
{
    public class SponsorModel
    {
        public int Id { get; set; }

        [DisplayName("First Name:")]
        public string FirstName { get; set; }

        [DisplayName("Last Name:")]
        public string LastName { get; set; }

        [DisplayName("Amount to sponsor:")]
        public int Amount { get; set; }

        public int SponsoredAnimalId { get; set; }

        [DisplayName("Sponsored Animal:")]
        public AnimalModel SponsoredAnimal { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ZooApp.Models;

namespace ZooApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SponsorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ZooApp.Models;
using ZooApp.Services;

namespace ZooApp.Controllers
{
    public class SponsorController : Controller
    {
        private readonly SponsorService _sponsorService;
        private readonly ZooService _zooService;
        public SponsorController(SponsorService sponsorService, ZooService zooService)
        {
            _sponsorService = sponsorService;
            _zooService = zooService;
        }
        // GET: SponsorController
        public ActionResult Index()
        {
            var result = _sponsorService.GetAll();
            return View(result);
        }

        // GET: SponsorController/Create
        public ActionResult Create()
        {
            SponsorFormModel sponsorFormModel = new SponsorFormModel(_zooService.GetAll());
            return View(sponsorFormModel);
        }

        // POST: SponsorController/Create
        [HttpPost]
        public ActionResult Create(SponsorModel sponsor)
        {
            _sponsorService.AddSponsor(sponsor);
            return RedirectToAction("Create");
        }

        // GET: SponsorController/Edit/5
        public ActionResult Edit(int id)
        {
            SponsorFormModel sponsor = _sponsorService.GetSingle(id);
            sponsor.Animals = _zooService.GetAll();
            return View(sponsor);
        }

        // POST: SponsorController/Edit/5
        [HttpPost]
        public ActionResult Edit(SponsorModel sponsor)
        {
            _sponsorService.EditSponsor(sponsor);
            return RedirectToAction("Index", "Sponsor");
        }

        // GET: SponsorController/Delete/5
        public ActionResult Delete(int id)
        {
            _sponsorService.DeleteSponsor(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ZooController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ZooApp.Models;
using ZooApp.Services;

namespace ZooApp.Controllers
{
    public class ZooController : Controller
    {
        private readonly ZooService _zooService;
        public ZooController(ZooService zooService)
        {
            _zooService = zooService;
        }
        // GET: ZooController
        public ActionResult Index()
        {
            var result = _zooService.GetAll();
            return View(result);
        }

        // GET: ZooController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ZooController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnimalModel animal)
        {
            _zooService.AddAnimal(animal);
            return RedirectToAction("Create");
        }

        // GET: ZooController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_zooService.GetSingle(id));
        }

        // POST: ZooController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnimalModel animal)
        {
            _zooService.EditAnimal(animal);
            return RedirectToAction("Index");
        }

        // GET: ZooController/Delete/5
        public ActionResult Delete(int id)
        {
            _zooService.DeleteAnimal(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZooApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZooApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zoo" asp-action="Index">Zoo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sponsor" asp-action="Index">Sponsors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ZooApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Sponsor/Create.cshtml
@model SponsorFormModel

@using (Html.BeginForm("Create", "Sponsor", FormMethod.Post))
{
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.FirstName, new { @class= "form-label" })
        @Html.TextBoxFor(sponsor => sponsor.FirstName, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.LastName, new { @class= "form-label" })
        @Html.TextBoxFor(sponsor => sponsor.LastName, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.Amount, new { @class= "form-label" })
        @Html.TextBoxFor(sponsor => sponsor.Amount, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.SponsoredAnimalId, new { @class= "form-label" })
        <select class="form-control" name="SponsoredAnimalId">
            @foreach (var animal in @Model.Animals)
            {
                <option value="@animal.Id">@animal.Name</option>
            }
        </select>
    </div>
    <div class="mb-3 col-5">
        <input type="submit" class="btn btn-primary" value="Submit" />
    </div>
}

Views/Sponsor/Edit.cshtml
@model SponsorFormModel

@using (Html.BeginForm("Edit", "Zoo", FormMethod.Post))
{
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.FirstName, new { @class= "form-label" })
        @Html.TextBoxFor(sponsor => sponsor.FirstName, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.LastName, new { @class= "form-label" })
        @Html.TextBoxFor(sponsor => sponsor.LastName, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.Amount, new { @class= "form-label" })
        @Html.TextBoxFor(sponsor => sponsor.Amount, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(sponsor => sponsor.SponsoredAnimal, new { @class= "form-label" })
        <select class="form-control" name="SponsoredAnimalId">
            @foreach (var animal in @Model.Animals)
            {
                @if (@Model.SponsoredAnimalId == @animal.Id)
                {
                    <option value="@animal.Id" selected>@animal.Name</option>
                }
                else
                {
                    <option value="@animal.Id">@animal.Name</option>
                }
            }
        </select>
    </div>
    <div class="mb-3 col-5">
        <input type="submit" class="btn btn-primary" value="Submit" />
    </div>
}

Views/Sponsor/Index.cshtml
@model List<SponsorModel>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Amount</th>
            <th>Sponsored Animal</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var sponsor in @Model)
        {
            <tr>
                <td>@sponsor.FirstName</td>
                <td>@sponsor.LastName</td>
                <td>@sponsor.Amount</td>
                <td>@sponsor.SponsoredAnimal.Name</td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Sponsor", new { id = sponsor.Id },  new { @class= "btn btn-primary" })
                    @Html.ActionLink("Edit", "Edit", "Sponsor", new { id = sponsor.Id },  new { @class= "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex w-100 justify-content-between">
    @Html.ActionLink("Create", "Create", "Sponsor", new {}, new { @class= "btn btn-primary" })
</div>

Views/Zoo/Create.cshtml
@model AnimalModel

@using (Html.BeginForm("Create", "Zoo", FormMethod.Post))
{
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Name, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Name, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Description, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Description, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Gender, new { @class= "form-label" })
        @Html.TextBoxFor(zoo => zoo.Gender, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Age, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Age, new { @class= "form-control", @type="number" })
    </div>
    <div class="mb-3 col-5">
        <input type="submit" class="btn btn-primary" value="Submit" />
    </div>
}

Views/Zoo/Edit.cshtml
@model AnimalModel

@using (Html.BeginForm("Edit", "Zoo", FormMethod.Post))
{
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Name, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Name, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Description, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Description, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Gender, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Gender, new { @class= "form-control" })
    </div>
    <div class="mb-3 col-5">
        @Html.LabelFor(animal => animal.Age, new { @class= "form-label" })
        @Html.TextBoxFor(animal => animal.Age, new { @class= "form-control", @type="number" })
    </div>
    <div class="mb-3 col-5">
        <input type="submit" class="btn btn-primary" value="Submit" />
    </div>
}

Views/Zoo/Index.cshtml
@model List<AnimalModel>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Gender</th>
            <th>Age</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var animal in @Model)
        {
            <tr>
                <td>@animal.Name</td>
                <td>@animal.Description</td>
                <td>@animal.Gender</td>
                <td>@animal.Age</td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Zoo", new { id = animal.Id },  new { @class= "btn btn-primary" })
                    @Html.ActionLink("Edit", "Edit", "Zoo", new { id = animal.Id },  new { @class= "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex w-100 justify-content-between">
    @Html.ActionLink("Create", "Create", "Zoo", new {}, new { @class= "btn btn-primary" })
</div>